# Generated by Django 5.1.2 on 2024-11-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empinfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
                ('designation', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
